@localBaseURL = http://localhost:3000
@hostBaseURL =  https://my-booking-hotel.herokuapp.com

# @name registerUser
# @note
# Email and phone number require unique
POST {{hostBaseURL}}/register
Content-Type: application/json

{
    "user_name": "oanh",
    "user_email": "oanh@gmail.com",
    "user_password": "123456",
    "confirm_password": "123456",
    "user_phone": "0948275555"
}

###

# @name login
POST {{localBaseURL}}/login
Content-Type: application/json

{
    "user_email": "oanh@gmail.com",
    "user_password": "1234asd"
}

### Login
POST {{hostBaseURL}}/login
Content-Type: application/json

{
    "user_email": "huyson203@gmail.com",
    "user_password": "asdasd"
}


###

# @name refreshToken
POST {{localBaseURL}}/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJkN2VjNDZhZi04ZTk0LTQ3OWEtOWNmMC0yOGY2NzIwYTBlM2UiLCJ1c2VyX2VtYWlsIjoiaHV5c29uMjAyQGdtYWlsLmNvbSIsInVzZXJfbmFtZSI6Imh1eSBzb24iLCJ1c2VyX3Bob25lIjoiMDE2NTQ4NzQ1IiwidXNlcl9yb2xlIjoxLCJjcmVhdGVkQXQiOiIyMDIxLTEwLTE4VDEyOjQ5OjMyLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTEwLTE4VDEzOjE0OjIxLjAwMFoiLCJpYXQiOjE2MzQ2MDI4NjAsImV4cCI6MTYzNTIwNzY2MH0.pOs94TVR2_voGy9mM0SohzjHbwdffZvGsf1Ip2wa-XI"
}

### Login
POST {{localBaseURL}}/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJmY2Q3NWNkMC1kNGZlLTQ2ZDktYjg5Ny1lNjY0NWE0NTZiM2EiLCJ1c2VyX2VtYWlsIjoiaHV5c29uQGdtYWlsLmNvbSIsInVzZXJfaW1nIjpudWxsLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9waG9uZSI6IjAxNjU0ODc0NSIsInVzZXJfcm9sZSI6MCwiaWF0IjoxNjM1MTcwNDEyLCJleHAiOjE2MzUxNzc2MTJ9.ec6rEWuooaA3GXBcZNv3lYgPRDJYiPkWGOHgcchsw6A

### 

# @name getAllHotels
GET {{localBaseURL}}/hotels
Authorization: Bearer

### 

# @name getHotelById
GET {{localBaseURL}}/hotels/1
Authorization: Bearer


### 

# @name getRoomOfHotel
GET {{localBaseURL}}/hotels/1/rooms
Authorization: Bearer

###

#  @name getHotelsOfUser
GET {{localBaseURL}}/users/e957686f-c38b-4731-b0ca-0182ad970bdc/hotels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJlOTU3Njg2Zi1jMzhiLTQ3MzEtYjBjYS0wMTgyYWQ5NzBiZGMiLCJ1c2VyX3JvbGUiOjEsImlhdCI6MTYzNTkyNDQ2MywiZXhwIjoxNjM1OTMxNjYzfQ.GkmYFmmiMVmLcQY8qfePj6h_eT_zs8nW9vn2bkqpIi0


###

# @name getAllRoom
GET {{localBaseURL}}/rooms

###

# @name getRoomById
GET {{localBaseURL}}/rooms/1

### 

# @name deleteRoom
# @note
# requrie params id 
DELETE  {{localBaseURL}}/rooms/:id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJlYWY3ZDU0NC1kYmIyLTRmYmYtOGYxZC0wNDNjNGNhMjYxNmYiLCJ1c2VyX2VtYWlsIjoiaHV5c29uMjAyQGdtYWlsLmNvbSIsInVzZXJfaW1nIjoiL2ltYWdlcy8wYTFiNzk1ZWFiNWE1YzAwMzhlMTQ1ODg4ZTJkYmYzYSIsInVzZXJfbmFtZSI6Im5ndXllbiBkb2FuIGh1eSBzb24gMTIzIiwidXNlcl9waG9uZSI6IjA5ODU0Nzg1NDc0IiwidXNlcl9yb2xlIjoxLCJpYXQiOjE2MzUyMDk2NzQsImV4cCI6MTYzNTIxNjg3NH0.B8vARCf62fZO_s1pnkJIymP3z7T0q8qOHArh5F2GOj8

{
    "hotel_id": 1,
}

###

# @name updateRoom
# @note
# send A form data
# image field name: slideImgs[] is a array images

PATCH {{localBaseURL}}/rooms/:id
Authorization: Bearer

### 

# @name getAllUsers
GET {{localBaseURL}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJmY2Q3NWNkMC1kNGZlLTQ2ZDktYjg5Ny1lNjY0NWE0NTZiM2EiLCJ1c2VyX2VtYWlsIjoiaHV5c29uQGdtYWlsLmNvbSIsInVzZXJfaW1nIjpudWxsLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9waG9uZSI6IjAxNjU0ODc0NSIsInVzZXJfcm9sZSI6MCwiaWF0IjoxNjM1MTcwNDQ0LCJleHAiOjE2MzUxNzc2NDR9.77koy-e38IB_v5ildf-pgwQDmvmTiZZRVjCi8QqcmFA


### 

# @name getUserById
GET {{localBaseURL}}/users/e957686f-c38b-4731-b0ca-0182ad970bdc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI2YzQyNzNlMC04ZjlmLTQ0NjUtYTc2MC1jMWJiYmYxNjMzYjAiLCJ1c2VyX3JvbGUiOjEsImlhdCI6MTYzNTc2OTkzOCwiZXhwIjoxNjM1Nzc3MTM4fQ.O0-fNZsNKwpVwgsfNcrGd__YDskMLgOp_pljCZXhW0k


### 

# @name deleteUser
DELETE  {{localBaseURL}}/users/48e34783-2270-4eab-a0b6-89aa47946731
Content-Type: application/json
Authorization: Bearer

###

# @name createUser
POST {{localBaseURL}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJmY2Q3NWNkMC1kNGZlLTQ2ZDktYjg5Ny1lNjY0NWE0NTZiM2EiLCJ1c2VyX2VtYWlsIjoiaHV5c29uQGdtYWlsLmNvbSIsInVzZXJfaW1nIjpudWxsLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9waG9uZSI6IjAxNjU0ODc0NSIsInVzZXJfcm9sZSI6MCwiaWF0IjoxNjM0NzE0NDc4LCJleHAiOjE2MzQ3MjE2Nzh9.yd3Jsxp1vmishzhycVWNZQRFMAcOQORNzncHY5WbWcE

{
    "user_name": "huy son",
    "user_email": "huyson4@gmail.com",
    "user_password": "123123",
    "user_phone": "016548745",
    "user_role": 0
}


###

# @name updateUser
# @note
# send a form data
# user image field name: avatar
PATCH {{localBaseURL}}/users/:uuid
Authorization: Bearer 


### 

# @name getAllStaff
GET {{localBaseURL}}/staffs


###

# @name getStaffById
GET {{localBaseURL}}/staffs/1

###

# @name getStaffOfHotel

# @note 
# only admin or hotel owner can get staff
GET {{localBaseURL}}/hotels/1/staffs
Authorization: Bearer

###

# @name getHotelOfStaff
GET {{localBaseURL}}/staffs/3/hotels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI5MTJiMWZmMC0wMDdjLTQ3NjItODYxZi1hMjNlNzJkZGRkMGMiLCJ1c2VyX3JvbGUiOjIsImlhdCI6MTYzNTkyNDg1NywiZXhwIjoxNjM1OTMyMDU3fQ.9m2aMv_8Jemfn8lEbvtaJF4eq8GNFfdmdKP11Jy-CUw
### 

# @name deleteStaff
# @note
# only owner of staff can delete staffs
DELETE {{localBaseURL}}/staffs/:id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJlYWY3ZDU0NC1kYmIyLTRmYmYtOGYxZC0wNDNjNGNhMjYxNmYiLCJ1c2VyX2VtYWlsIjoiaHV5c29uMjAyQGdtYWlsLmNvbSIsInVzZXJfaW1nIjoiL2ltYWdlcy8wYTFiNzk1ZWFiNWE1YzAwMzhlMTQ1ODg4ZTJkYmYzYSIsInVzZXJfbmFtZSI6Im5ndXllbiBkb2FuIGh1eSBzb24gMTIzIiwidXNlcl9waG9uZSI6IjA5ODU0Nzg1NDc0IiwidXNlcl9yb2xlIjoxLCJpYXQiOjE2MzUxNzE3NzQsImV4cCI6MTYzNTE3ODk3NH0.cUUJ8h3Xw_vRfg4s4XQPhVfcysqYcnxLvlalQ1u7Vys


### 

# @name createStaff
POST {{localBaseURL}}/staffs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI4NDYxZTk1OS0yYTMzLTQyNGItYTQwYy0yOGU4YTFiYjU4MDMiLCJ1c2VyX3JvbGUiOjEsImlhdCI6MTYzNjQyODY0MCwiZXhwIjoxNjM2NDM1ODQwfQ.w0NzyyjwJSUVGsLu7ZHn2Njf_76lOBPto-j89e5dumo

{
    "user_name": "staff20",
    "user_email": "staff20@gmail.com",
    "user_password": "123123",
    "user_role": 2,
    "user_phone": "016541743",
    "staff_role": 0,
    "hotel_id": 1
    
}


###

# @name updateStaff
# @note
# updating data is a json
PATCH {{localBaseURL}}/staffs/:id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI5MTJiMWZmMC0wMDdjLTQ3NjItODYxZi1hMjNlNzJkZGRkMGMiLCJ1c2VyX3JvbGUiOjIsImlhdCI6MTYzNTkyNDg1NywiZXhwIjoxNjM1OTMyMDU3fQ.9m2aMv_8Jemfn8lEbvtaJF4eq8GNFfdmdKP11Jy-CUw



### 

# @name getInvoicesByUserId
GET {{localBaseURL}}/users/eaf7d544-dbb2-4fbf-8f1d-043c4ca2616f/invoices
Authorization: Bearer

###

# @name getInvoicesOfHotel

# @note
# status query ?status=
GET {{localBaseURL}}/hotels/3/invoices?status=Chua xac nhan

###

# @name getAllInvoices

# @note
# status query ?status=
GET {{localBaseURL}}/invoices?status="Chưa xác nhận"


###

# @name getInvoiceById
GET {{localBaseURL}}/invoices/1

### 

# @name createInvoice
POST {{hostBaseURL}}/invoices
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI3MjYyODk1YS0xMzkxLTRkZTYtYWRiMi1hNTgwNzA4NTlmMTQiLCJ1c2VyX3JvbGUiOjIsImlhdCI6MTYzNjM2MDUzNiwiZXhwIjoxNjM2MzY3NzM2fQ.iQ0Wq8cO1Nf22UwT4NXO1nNekL4p1nUeQmIBBnTvk-E

{
    "price" : "120000",
    "hotel_id": 3,
    "r_date": "2021-10-21T12:00:00",
    "p_date": "2021-10-21T12:00:00",
    "room_id": 11,
    "room_quantity": 1,
    "status": 0
}

###

# @name updateInvoice
PATCH {{localBaseURL}}/invoices/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJlMzE0NDJhYi0wYWE2LTQxNjAtODU2Ni0xNzVmYmJmMTJhN2EiLCJ1c2VyX2VtYWlsIjoiaHV5c29uMjAwQGdtYWlsLmNvbSIsInVzZXJfaW1nIjpudWxsLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9waG9uZSI6IjAxNjU0ODc0NSIsInVzZXJfcm9sZSI6MiwiaWF0IjoxNjM1MjEyMzAzLCJleHAiOjE2MzUyMTk1MDN9.Z5vCbenPAYKEByYcU1AaOCc7CtGMGHbnFVTiYw0ixyU

{
    "status": "hoan thanh",
    "room_quantity": 3
}

###

# @name deleteInvoice

DELETE {{localBaseURL}}/invoices/22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI3MjYyODk1YS0xMzkxLTRkZTYtYWRiMi1hNTgwNzA4NTlmMTQiLCJ1c2VyX3JvbGUiOjIsImlhdCI6MTYzNjM1MjA2MiwiZXhwIjoxNjM2MzU5MjYyfQ.PoRWD25GpRUvmeKKhdxERR5NSbg4op82ApHJNBGgfV8
### send otp

POST {{localBaseURL}}/send-otp
Content-Type: application/json

{
    "to" : "huyson201@gmail.com",
    "channel": "email"
}

### verify otp
post {{localBaseURL}}/verify-otp
Content-Type: application/json

{
    "to" : "huyson201@gmail.com",
    "code": "9806"
}

### rest password

PATCH {{localBaseURL}}/reset-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJlOTU3Njg2Zi1jMzhiLTQ3MzEtYjBjYS0wMTgyYWQ5NzBiZGMiLCJpYXQiOjE2MzUzMjkwMDMsImV4cCI6MTYzNTMyOTMwM30.AfHar7FeKv9m8QOAN1_8H9yXRD2eJnOQMVtbhENfEQE

{
    "new_password" : "huyson123",
    "confirm_password": "huyson123"
}