POST http://localhost:3000/register
Content-Type: application/json

{
    "user_name": "huy son",
    "user_email": "huyson2@gmail.com",
    "user_password": "123123",
    "confirm_password": "123123",
    "user_phone": "016548745"
}

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "user_email": "huyson202@gmail.com",
    "user_password": "123123"
}


### refresh token
POST http://localhost:3000/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJkN2VjNDZhZi04ZTk0LTQ3OWEtOWNmMC0yOGY2NzIwYTBlM2UiLCJ1c2VyX2VtYWlsIjoiaHV5c29uMjAyQGdtYWlsLmNvbSIsInVzZXJfbmFtZSI6Imh1eSBzb24iLCJ1c2VyX3Bob25lIjoiMDE2NTQ4NzQ1IiwidXNlcl9yb2xlIjoxLCJjcmVhdGVkQXQiOiIyMDIxLTEwLTE4VDEyOjQ5OjMyLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTEwLTE4VDEzOjE0OjIxLjAwMFoiLCJpYXQiOjE2MzQ2MDI4NjAsImV4cCI6MTYzNTIwNzY2MH0.pOs94TVR2_voGy9mM0SohzjHbwdffZvGsf1Ip2wa-XI"
}

### Login
POST http://localhost:3000/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI1Mjg3NDg0NC0yNWZiLTRiMDAtODBlZi1mNWVlYmVhMmVmZTUiLCJ1c2VyX2VtYWlsIjoiaHV5c29uMjAyQGdtYWlsLmNvbSIsInVzZXJfbmFtZSI6Imh1eSBzb24iLCJ1c2VyX3Bob25lIjoiMDE2NTQ4NzQ1IiwidXNlcl9yb2xlIjoxLCJjcmVhdGVkQXQiOiIyMDIxLTEwLTE5VDAwOjM4OjM5LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTEwLTE5VDAwOjM4OjM5LjAwMFoiLCJpYXQiOjE2MzQ2MDM5MjIsImV4cCI6MTYzNDYxMTEyMn0.S-LeCyL6jZzdFB7S38nmveCpd-iWmUuDHRe7XDu8zd4

### get list hotels
GET http://localhost:3000/hotels

### get hotel by id = 1
GET http://localhost:3000/hotels/1

### get all rooms of  hotel
GET http://localhost:3000/hotels/12/rooms


### get all rooms
GET http://localhost:3000/rooms

### get rooms by id
GET http://localhost:3000/rooms/1

### get users
GET http://localhost:3000/users

### get users by id
GET http://localhost:3000/users/48e34783-2270-4eab-a0b6-89aa47946731

### delete user by id
DELETE  http://localhost:3000/users
Content-Type: application/json

{
    "delete_id": "48e34783-2270-4eab-a0b6-89aa47946731"
}

### create user 
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJmY2Q3NWNkMC1kNGZlLTQ2ZDktYjg5Ny1lNjY0NWE0NTZiM2EiLCJ1c2VyX2VtYWlsIjoiaHV5c29uQGdtYWlsLmNvbSIsInVzZXJfaW1nIjpudWxsLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9waG9uZSI6IjAxNjU0ODc0NSIsInVzZXJfcm9sZSI6MCwiaWF0IjoxNjM0NzE0NDc4LCJleHAiOjE2MzQ3MjE2Nzh9.yd3Jsxp1vmishzhycVWNZQRFMAcOQORNzncHY5WbWcE

{
    "user_name": "huy son",
    "user_email": "huyson4@gmail.com",
    "user_password": "123123",
    "user_phone": "016548745",
    "user_role": 0
}

### get staffs
GET http://localhost:3000/staffs


### get staff by id
GET http://localhost:3000/staffs/1

### get staff of hotel
GET http://localhost:3000/hotels/1/staffs


### delete a staff
DELETE http://localhost:3000/staffs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJjNWQyZjc2Yi04MGJmLTQ1ZjgtYWNjZC03NTQ2ZDc0ZGYwYTMiLCJ1c2VyX2VtYWlsIjoiaHV5c29uMjAyQGdtYWlsLmNvbSIsInVzZXJfbmFtZSI6Imh1eSBzb24iLCJ1c2VyX3Bob25lIjoiMDE2NTQ4NzQ1IiwidXNlcl9yb2xlIjoxLCJjcmVhdGVkQXQiOiIyMDIxLTEwLTE5VDAzOjMxOjAwLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTEwLTE5VDAzOjMxOjAwLjAwMFoiLCJpYXQiOjE2MzQ2MTQyOTEsImV4cCI6MTYzNDYyMTQ5MX0.JbKz-19PY-qEMY8wSFFSBkRyHkSTDjcSg9WoVKMgLG8

{
    "hotel_id": 1,
    "staff_id": 4
}

### create a staff
POST http://localhost:3000/staffs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJjNWQyZjc2Yi04MGJmLTQ1ZjgtYWNjZC03NTQ2ZDc0ZGYwYTMiLCJ1c2VyX2VtYWlsIjoiaHV5c29uMjAyQGdtYWlsLmNvbSIsInVzZXJfbmFtZSI6Imh1eSBzb24iLCJ1c2VyX3Bob25lIjoiMDE2NTQ4NzQ1IiwidXNlcl9yb2xlIjoxLCJjcmVhdGVkQXQiOiIyMDIxLTEwLTE5VDAzOjMxOjAwLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTEwLTE5VDAzOjMxOjAwLjAwMFoiLCJpYXQiOjE2MzQ2MTQyOTEsImV4cCI6MTYzNDYyMTQ5MX0.JbKz-19PY-qEMY8wSFFSBkRyHkSTDjcSg9WoVKMgLG8

{
    "user_name": "huy son",
    "user_email": "huyson200@gmail.com",
    "user_password": "123123",
    "user_role": 2,
    "user_phone": "016548745",
    "staff_role": 2,
    "hotel_id": 1
    
}


### get invoices
GET http://localhost:3000/invoices


### get invoice by id
GET http://localhost:3000/invoices/1

### get invoice of a user
GET http://localhost:3000/users/eaf7d544-dbb2-4fbf-8f1d-043c4ca2616f/invoices

### create a invoice
POST http://localhost:3000/invoices
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJlYWY3ZDU0NC1kYmIyLTRmYmYtOGYxZC0wNDNjNGNhMjYxNmYiLCJ1c2VyX2VtYWlsIjoiaHV5c29uMjAyQGdtYWlsLmNvbSIsInVzZXJfaW1nIjoiL2ltYWdlcy8wYTFiNzk1ZWFiNWE1YzAwMzhlMTQ1ODg4ZTJkYmYzYSIsInVzZXJfbmFtZSI6Im5ndXllbiBkb2FuIGh1eSBzb24gMTIzIiwidXNlcl9waG9uZSI6IjA5ODU0Nzg1NDc0IiwidXNlcl9yb2xlIjoxLCJpYXQiOjE2MzQ3MTU2NzUsImV4cCI6MTYzNDcyMjg3NX0.1GLbcxYs0Mj13TWeWPFsYrNb_QGGMglJrOn8fg5hU_c

{
    "price" : "120000",
    "hotel_id": 1,
    "r_date": "2021-10-20T12:00:00",
    "p_date": "2021-10-21T12:00:00",
    "room_id": 12,
    "room_quantity": 1,
    "status": "Dang dat coc"
}

